### ISSUE TITLE
GUI workflow

### ISSUE THREAD

**Issue by JeltevanBoheemen** [UUDigitalHumanitieslab/TrEd-bridge#11]
Coming from TrEd (filepath of XML):

- [x] 1. Read & parse XML from path. Extract utterance. #14
- [x] 2. Record as `(ask Jan)` to the XML and pass on. #14
- [x] 3. Manual & assisted editing of the utterance. CHAMD cleaning allowed.
- [x] 4. Continue -> Enforce CHAMD clean. #15 
- [x] 5. Record (cleaned/pre-cleaned/both?) state as `(ask Jan)` to the XML. #14
- [x] 6. Manual & assisted editing of ALPINO enrichment syntax.
- [x] 7. Cleanup/tokenize -> parse with Alpino.  Ideally give feedback. #13 
- [x] 8. Record as `ask Jan` to the XML. #14
- [x] 9. Save & Exit -> Save the altered XML. #14

Continue to TrEd.
